RMA SITE CSHARP/Controllers/Admin/AgentAdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RMA_SITE.Models;
using PagedList;

namespace RMA_SITE.Controllers.Admin
{
    [Authorize(Roles = "admin")]
    public class AgentAdminController : Controller
    {
        private RMA_DBContext db = new RMA_DBContext("RMA_DBContext");

        // GET: AgentAdmin
        public ActionResult Index(int? page)
        {

            IEnumerable<RMA_SITE.Models.Agent> agents = db.Agents.ToList();
            agents = agents.OrderByDescending(s => s.average_overall_rating_cache);

            int pageSize = 10;
            int pageNumber = (page ?? 1);

            return View(agents.ToPagedList(pageNumber, pageSize));


        }


        // GET: AgentAdmin/Search
        public ActionResult Search(string param, string v, string sortorder, int? page)
        {


            ViewBag.Message = "Search Results.";

            if (param == "#") { param = ""; }
            ViewBag.CurrentFilter = param;
            if (ViewBag.CurrentFilter == "") { ViewBag.CurrentFilter = "#"; }

            ViewBag.CurrentSort = sortorder;


            var search_terms = param.Split(' ').ToList();

            List<Agent> agents = new List<Agent>();

            foreach (string search_term in search_terms)
            {

                var curr_agents = db.Agents.Where(s => (s.first_name.Contains(search_term) || s.last_name.Contains(search_term) || s.city.Contains(search_term)));

                agents = agents.Union(curr_agents).ToList();

            }



            var qagents = agents.AsQueryable();

            if (v == "l")
            {
                return View("Index", qagents);
            }
            else
            {
                switch (sortorder)
                {
                    case "name_desc":
                        qagents = qagents.OrderByDescending(s => s.first_name);
                        break;

                }


                int pageSize = 10;
                int pageNumber = (page ?? 1);
                return View("Index", qagents.ToPagedList(pageNumber, pageSize));
                //return View(agents.ToPagedList(pageNumber, pageSize));
            }

        }


        // GET: AgentAdmin/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agent agent = db.Agents.Find(id);
            if (agent == null)
            {
                return HttpNotFound();
            }
            return View(agent);
        }

        // GET: AgentAdmin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AgentAdmin/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,RMA_ID,photo_content,agent_type,first_name,last_name,phone_number,cell_number,fax_number,address1,address2,city,prov_state,country,email,web_site,company_name,created_at,updated_at,average_overall_rating_cache,average_overall_ranking,total_review_count,active,photo_filename,photo_link")] Agent agent)
        {
            if (ModelState.IsValid)
            {
                db.Agents.Add(agent);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(agent);
        }

        // GET: AgentAdmin/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agent agent = db.Agents.Find(id);
            if (agent == null)
            {
                return HttpNotFound();
            }
            return View(agent);
        }

        // POST: AgentAdmin/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,RMA_ID,photo_content,agent_type,first_name,last_name,phone_number,cell_number,fax_number,address1,address2,city,prov_state,country,email,web_site,company_name,created_at,updated_at,average_overall_rating_cache,average_overall_ranking,total_review_count,active,photo_filename,photo_link")] Agent agent)
        {
            if (ModelState.IsValid)
            {
                db.Entry(agent).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(agent);
        }

        // GET: AgentAdmin/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Agent agent = db.Agents.Find(id);
            if (agent == null)
            {
                return HttpNotFound();
            }
            return View(agent);
        }

        // POST: AgentAdmin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Agent agent = db.Agents.Find(id);
            db.Agents.Remove(agent);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RMA SITE CSHARP/Views/AgentAdmin/Create.cshtml
@model RMA_SITE.Models.Agent

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Agent</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RMA_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RMA_ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RMA_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.photo_content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.photo_content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.photo_content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.agent_type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.agent_type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.agent_type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.first_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.first_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.first_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.last_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.last_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.last_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phone_number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phone_number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone_number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cell_number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cell_number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cell_number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fax_number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fax_number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fax_number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.address1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.address1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.address2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.address2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.city, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.city, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.city, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prov_state, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prov_state, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prov_state, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.web_site, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.web_site, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.web_site, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.company_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.company_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.company_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.created_at, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.created_at, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.created_at, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.updated_at, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.updated_at, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.updated_at, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.average_overall_rating_cache, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.average_overall_rating_cache, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.average_overall_rating_cache, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.average_overall_ranking, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.average_overall_ranking, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.average_overall_ranking, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.total_review_count, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.total_review_count, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.total_review_count, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.active, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.active, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.photo_filename, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.photo_filename, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.photo_filename, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.photo_link, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.photo_link, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.photo_link, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", null, null, null, new { href = Request.UrlReferrer })
</div>

RMA SITE CSHARP/Views/AgentAdmin/Delete.cshtml
@model RMA_SITE.Models.Agent

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Agent</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RMA_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RMA_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.photo_content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.photo_content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.agent_type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.agent_type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.first_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.first_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.last_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.last_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phone_number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phone_number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cell_number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cell_number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fax_number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fax_number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.city)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.city)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prov_state)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prov_state)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.web_site)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.web_site)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.company_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.company_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.created_at)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.created_at)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.updated_at)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.updated_at)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.average_overall_rating_cache)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.average_overall_rating_cache)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.average_overall_ranking)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.average_overall_ranking)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.total_review_count)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.total_review_count)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.photo_filename)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.photo_filename)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.photo_link)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.photo_link)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <p>
            !! THIS ACTION CANNOT BE REVERSED !!
        </p>
        <div class="form-actions no-color">
            
            @Html.ActionLink("Cancel / Back to List", null, null, null, new { href = Request.UrlReferrer }) |
            <input type="submit" value="Confirm Delete" class="btn btn-default" /> 

        </div>
    }
</div>

RMA SITE CSHARP/Views/AgentAdmin/Details.cshtml
@model RMA_SITE.Models.Agent

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Agent</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RMA_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RMA_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.photo_content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.photo_content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.agent_type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.agent_type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.first_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.first_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.last_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.last_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phone_number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phone_number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cell_number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cell_number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fax_number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fax_number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.city)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.city)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.prov_state)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prov_state)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.web_site)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.web_site)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.company_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.company_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.created_at)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.created_at)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.updated_at)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.updated_at)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.average_overall_rating_cache)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.average_overall_rating_cache)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.average_overall_ranking)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.average_overall_ranking)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.total_review_count)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.total_review_count)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.active)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.photo_filename)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.photo_filename)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.photo_link)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.photo_link)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", null, null, null, new { href = Request.UrlReferrer })
    
</p>

RMA SITE CSHARP/Views/AgentAdmin/Index.cshtml
@model PagedList.IPagedList<RMA_SITE.Models.Agent>

@{
    ViewBag.Title = "Agent Admin";
}

<h2>Agent Administration</h2>


   


@using (Html.BeginForm("Search", "AgentAdmin", FormMethod.Get))
            {
    @Html.ActionLink("Create New ", "Create")    
    @Html.TextBox("param")
    @Html.Hidden("sortorder", "")
    <input type="submit" value="Search" />
}

<br />
@Html.Partial("_AgentListItemPartial", Model)

RMA SITE CSHARP/Views/AgentAdmin/_AgentListItemPartial.cshtml
@model PagedList.IPagedList<RMA_SITE.Models.Agent>
@using PagedList.Mvc;


<div style="border:solid 0px #808080; margin: auto; text-align:center;">
   
    @if (Model.Count() > 0)
    {

        <div style="display:block; border:solid 0px #899980;">
            <table>
                <tr>
                    <th>
                        Agent ID
                    </th>
                    <th style="width:125px">

                    </th>
                    <th style="width:200px">
                        Name
                    </th>

                    <th style="width:150px">
                        City
                    </th>

                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.RMA_ID)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.agent_type)
                        </td>

                        <td style="text-align:left">
                            @Html.DisplayFor(modelItem => item.first_name) @Html.DisplayFor(modelItem => item.last_name)
                        </td>
                        <td style="text-align:left">
                            @Html.DisplayFor(modelItem => item.city), @Html.DisplayFor(modelItem => item.prov_state)
                        </td>
                        <td></td>


                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                            @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                        </td>
                    </tr>
                }

            </table>
        </div>



            <nav class="category-pagination">
                <div style="text-align:left;">
                    @Html.PagedListPager(Model, page => Url.Action(ViewBag.ControllerName, new { page, param = ViewBag.CurrentFilter, sortorder = ViewBag.CurrentSort }))
                    @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                </div>
            </nav> 
        
    }
    else
    {
        <div><br />Empty.</div>
    }

</div>

<br style="clear:both" />