RMA SITE CSHARP/Controllers/CityController.cs
using PagedList;
using RMA_SITE.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;



namespace RMA_SITE.Controllers
{


    public class CityController : Controller
    {
        string Capitalize(string source_string)
        {
            if (source_string.Length > 1)
            {
                return source_string.ToUpper().Substring(0, 1) + source_string.ToLower().Substring(1);
            }
            else
            {
                return source_string.ToUpper();
            }
        }

        private RMA_DBContext db = new RMA_DBContext("RMA_DBContext");
        int pageSize = 12;

        // GET: City
        public ActionResult Index(string city, string prov, int? page)
        {
            ViewBag.Title = Capitalize(city) + ", " + prov.ToUpper() + ", Ratings and Reviews";
            ViewBag.MetaDescription = "Agent ratings and reviews in " + Capitalize(city) + ", " + prov.ToUpper();
            ViewBag.ControllerName = "Index";

            ViewBag.City = city;
            ViewBag.Province = prov;
            
            City selected_city = db.Cities.Where(g => (g.name == city & g.prov_state == prov)).FirstOrDefault();
            if (selected_city != null) { ViewBag.CityPageContent = selected_city.description; }
            if(ViewBag.CityPageContent == "NULL") { ViewBag.CityPageContent = ""; }

            ViewBag.Message = "Top " + Capitalize(city) + ", " + prov.ToUpperInvariant() + " Agents Ratings and Reviews";

            var agents = db.Agents.Where(s => (s.city.Contains(city)));
            agents = agents.OrderByDescending(s => s.cumulative_rating);


            int pageNumber = (page ?? 1);

            return View(agents.ToPagedList(pageNumber, pageSize));

        }

     public ActionResult Mortgage(string city, string prov, int? page)
        {
            ViewBag.Title = Capitalize(city) + ", " + prov.ToUpper() + ", Mortgage Broker Ratings and Reviews";
            ViewBag.MetaDescription = "Mortgage Broker ratings and reviews in " + Capitalize(city) + ", " + prov.ToUpper();
            ViewBag.ControllerName = "Mortgage";

            ViewBag.City = city;
            ViewBag.Province = prov;

            City selected_city = db.Cities.Where(g => (g.name == city & g.prov_state == prov)).FirstOrDefault();
            if (selected_city != null) { ViewBag.CityPageContent = selected_city.desc_mortgage; }
            if (ViewBag.CityPageContent == null) { ViewBag.CityPageContent = ""; }


            ViewBag.Message = "Top " + Capitalize(city) + ", " + prov.ToUpperInvariant() + " Mortgage Brokers - Ratings and Reviews";

            var agents = db.Agents.Where(s => (s.city.Contains(city)) & (s.agent_type.Contains("Mortgage")));
            agents = agents.OrderByDescending(s => s.cumulative_rating);

         
            int pageNumber = (page ?? 1);

            return View(agents.ToPagedList(pageNumber, pageSize));

        }

        public ActionResult Insurance(string city, string prov, int? page)
        {
            ViewBag.Title = Capitalize(city) + ", " + prov.ToUpper() + ", Insurance Agent Ratings and Reviews";
            ViewBag.MetaDescription = "Insurance Agent ratings and reviews in " + Capitalize(city) + ", " + prov.ToUpper();
            ViewBag.ControllerName = "Insurance";

            ViewBag.City = city;
            ViewBag.Province = prov;

            City selected_city = db.Cities.Where(g => (g.name == city & g.prov_state == prov)).FirstOrDefault();
            if (selected_city != null) { ViewBag.CityPageContent = selected_city.desc_insurance; }
            if (ViewBag.CityPageContent == null) { ViewBag.CityPageContent = ""; }

            ViewBag.Message = "Top " + Capitalize(city) + ", " + prov.ToUpperInvariant() + " Insurance Agents - Ratings and Reviews";

            var agents = db.Agents.Where(s => (s.city.Contains(city)) & (s.agent_type.Contains("Insurance")));
            agents = agents.OrderByDescending(s => s.cumulative_rating);

           
            int pageNumber = (page ?? 1);

            return View(agents.ToPagedList(pageNumber, pageSize));

        }

        public ActionResult RealEstate(string city, string prov, int? page)
        {
            ViewBag.Title = Capitalize(city) + ", " + prov.ToUpper() + ", Real Estate Agent Ratings and Reviews";
            ViewBag.MetaDescription = "Real Estate Agent ratings and reviews in " + Capitalize(city) + ", " + prov.ToUpper();
            ViewBag.ControllerName = "RealEstate";

            ViewBag.City = city;
            ViewBag.Province = prov;

            City selected_city = db.Cities.Where(g => (g.name == city & g.prov_state == prov)).FirstOrDefault();
            if (selected_city != null) { ViewBag.CityPageContent = selected_city.desc_realty; }
            if (ViewBag.CityPageContent == null) { ViewBag.CityPageContent = ""; }

            ViewBag.Message = "Top " + Capitalize(city) + ", " + prov.ToUpperInvariant() + " Real Estate Agents - Ratings and Reviews";

            var agents = db.Agents.Where(s => (s.city.Contains(city)) & (s.agent_type.Contains("Real")));
            agents = agents.OrderByDescending(s => s.cumulative_rating);

           
            int pageNumber = (page ?? 1);

            return View(agents.ToPagedList(pageNumber, pageSize));

        }

        public ActionResult Agents(string id)
        {
            ViewBag.City = id;
            return View();
        }

      

    }
}

RMA SITE CSHARP/Views/Shared/Info.cshtml
@{
   ViewBag.Title = "Info";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

RMA SITE CSHARP/Views/Shared/_AgentProfilePartial.cshtml
@model RMA_SITE.Models.ViewModelAgent




<span itemscope itemtype="http://schema.org/Review">

    <div class="page-content page-single">
        <div class="container">
            <div class="page-title-wrap">

                    <h1 class="page-title">@DataRichHelper.DataRich(Model.Agent.first_name + " " + Model.Agent.last_name, "name", "itemReviewed", "Person")</h1>

                <div class="page-title-desc">

                    @switch (Model.Agent.agent_type)
                    {
                        case "Real Estate":
                            @Html.ActionLink(Model.Agent.city + ", " + Model.Agent.prov_state + " Real Estate Agent Reviews and Ratings", "RealEstate", "City", new { city = @Model.Agent.city.ToLower(), prov = @Model.Agent.prov_state.ToLower() }, null);
                            break;
                        case "Insurance":
                            @Html.ActionLink(Model.Agent.city + ", " + Model.Agent.prov_state + " Insurance Agent Reviews and Ratings", "Insurance", "City", new { city = @Model.Agent.city.ToLower(), prov = @Model.Agent.prov_state.ToLower() }, null);
                            break;
                        case "Mortgage":
                            @Html.ActionLink(Model.Agent.city + ", " + Model.Agent.prov_state + " Mortgage Broker Reviews and Ratings", "Mortgage", "City", new { city = @Model.Agent.city.ToLower(), prov = @Model.Agent.prov_state.ToLower() }, null);
                            break;
                    }


                    @*@Html.ActionLink("Find other [" + @Model.Agent.city.ToUpperInvariant() + ", " + Model.Agent.prov_state.ToUpperInvariant() + "] - Insurance Agents Reviews and Ratings", "Insurance", "City", new { city = @Model.Agent.city.ToLower(), prov = @Model.Agent.prov_state.ToLower() }, null)*@
                    @*<a href="#">Saskatoon, SK, Real Estate Agent Reviews and Ratings</a>*@



                </div>
            </div>


            @*<span itemprop="name">@Model.Agent.city + ", " + @Model.Agent.prov_state</span>*@





            <div class="row">
                <div class="col-md-8">
                    <div class="single-info">
                        <div class="row">
                            <div class="col-md-5 col-sm-5">
                                <div class="single-photo">
                                    <img src="@Html.DisplayFor(modelItem => Model.Agent.photo_path)" width="225" height="340" />
                                </div>
                            </div>
                            <div class="col-md-7 col-sm-7">
                                <table class="table single-info-table">
                                    <tbody>
                                        <tr>
                                            <td>Email Address </td>
                                            <td>@Html.Raw(Model.Agent.email)</td>
                                        </tr>
                                        <tr>
                                            <td>Website </td>
                                            <td>@Html.Raw(Model.Agent.web_site)</td>
                                        </tr>
                                        <tr>
                                            <td>Company </td>
                                            <td>@Html.Raw(Model.Agent.company_name)</td>
                                        </tr>
                                        <tr>
                                            <td>Phone </td>
                                            <td>@Html.Raw(Model.Agent.phone_number)</td>
                                        </tr>
                                        <tr>
                                            <td>Cell </td>
                                            <td>@Html.Raw(Model.Agent.cell_number)</td>
                                        </tr>
                                        <tr>
                                            <td>Fax </td>
                                            <td>@Html.Raw(Model.Agent.fax_number)</td>
                                        </tr>
                                        <tr>
                                            <td>Address </td>
                                            <td>@Html.Raw(Model.Agent.address1)</td>
                                        </tr>
                                    </tbody>
                                </table>
                                <p>
                                    Is the contact info for this Real Estate Agent incorrect?
                                    <br /><a href="#">Click here to tell us how to fix it.</a>
                                </p>
                            </div>

                        </div>



                    </div>


                    @Html.Partial("_AgentSummaryPartial", Model.ReviewsSummary)

                </div>
                @Html.Partial("_SideRatingPartial", Model)

            </div>





            @Html.Partial("_AgentReviewsPartial")

        </div>
    </div>
</span>

RMA SITE CSHARP/Views/Shared/_AgentTilePartial.cshtml
@model RMA_SITE.Models.Agent
@using RMA_SITE.Helpers


    <div class="col-md-4 col-sm-6">
        <div class="panel panel-default card-agent">
            <div class="panel-body">
                <div class="card-img pull-left"><img src="@Model.photo_path" /></div>
                <div class="card-header pull-left">
                    <div class="card-name">@Html.ActionLink(Model.first_name + " " + Model.last_name, "Profiles", "Agents", new { id = Model.first_name.ToLower() + "-" + Model.last_name.ToLower(), city = Model.city.ToLower(), agent_id = Model.RMA_ID }, null) </div>
                    <div class="card-location">@Html.DisplayFor(modelItem => Model.city), @Html.DisplayFor(modelItem => Model.prov_state)</div>
                    <div class="card-rate">
                        <div class="star-rating star-rating-static">
                                                       
                            @for (var i = 10; i > 0; i--)
                            {
                                var tclass = i % 2;
                                var starcount = i / 2;
                                var tdatastar = "full";
                                var ischecked = "";

                                if((i*5 ) <= (Model.average_overall_rating_cache * 10))
                                {
                                    ischecked = "checked=\"\"";
                                }

                                if (tclass > 0) { tdatastar = "half"; }

                                @Html.Raw("<input type=\"radio\" " + ischecked  + "/><label class=\"" + tdatastar + "\" data-star=\"star" + starcount +  tdatastar + "\"></label>")
                            
                                

                            }

                            @Html.DisplayFor(modelItem => Model.cumulative_rating).If(User.IsInRole("admin"))
                        </div>
                        @*&nbsp; @Html.DisplayFor(modelItem => Model.average_overall_rating_cache)*@
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="card-review">
                    @*My experience with Paul was awful. He lied to us about the house having air conditioning when we initally looked at our home. We...*@
                </div>
            </div>
        </div>
    </div>


    @*<div style="width:150px; height:225px; border:solid 0px #808080; display:inline-block; ">

            <table style="width:125px;  height:215px; border:solid 0px #808080;">

                <tr>
                    <td colspan="2">
                        <img src="@Model.photo_path" width="125" height="125" />
                    </td>
                </tr>

                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => Model.agent_type)
                    </td>
                    <td>


                        @Html.ActionLink(Model.first_name + " " + Model.last_name, "Profiles", "Agents", new { id = Model.first_name.ToLower() + "-" + Model.last_name.ToLower(), city = Model.city.ToLower(), agent_id = Model.RMA_ID }, null)

                    </td>
                </tr>

                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => Model.city), @Html.DisplayFor(modelItem => Model.prov_state)
                    </td>

                    <td align="right">

                        @Html.DisplayFor(modelItem => Model.average_overall_rating_cache)
                        <div>
                            @for (var i = 0; i < Model.average_overall_rating_cache; i++)
                            {
                                <text>*</text>
                            }
                        </div>
                    </td>
                </tr>

            </table>
        </div>*@

RMA SITE CSHARP/Views/Shared/_ExternalLoginsListPartial.cshtml
@model RMA_SITE.Models.ExternalLoginListViewModel
@using Microsoft.Owin.Security

<h4>Use another service to log in...</h4>
<hr />
@{
    var loginProviders = Context.GetOwinContext().Authentication.GetExternalAuthenticationTypes();
    if (loginProviders.Count() == 0) {
        <div>
            <p>
                - Not available.
            </p>
        </div>
    }
    else {
        using (Html.BeginForm("ExternalLogin", "Account", new { ReturnUrl = Model.ReturnUrl }))
        {
            @Html.AntiForgeryToken()
            <div id="socialLoginList">
                <p>
                    @{ var str_image_path = ""; }
                    @foreach (AuthenticationDescription p in loginProviders) {
                        
                        switch (p.AuthenticationType){ 
                            case "Facebook":
                                str_image_path  = @Url.Content("~/Resources/login_facebook.png");

                                break;
                            case "Google":
                                str_image_path = @Url.Content("~/Resources/login_google.jpg");
                                break;
                        }


                        // <button type="submit" im class="btn btn-default" id="@p.AuthenticationType" name="provider" value="@p.AuthenticationType" title="Log in using your @p.Caption account">@p.AuthenticationType</button>

                        <input type="image" style="margin:10px;"  id="@p.AuthenticationType" name="provider" value="@p.AuthenticationType" src="@str_image_path" alt="Sign-In with @p.AuthenticationType" width="64px" height="64px" />

                    }
                </p>
            </div>
        }
    }
}

RMA SITE CSHARP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    @if (ViewBag.MetaDescription != "")
    {
        <meta name="description" content="@ViewBag.MetaDescription" />
    }

    @if (ViewBag.CanonicalUrl != "")
    {
        <link rel="canonical" href="@ViewBag.CanonicalUrl" />
    }
       
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>

  


    @Html.Partial("_LayoutHeaderPartial")


    

    <div class="site-main">
        <div class="main-content">
            <div class="container">

                @RenderBody()


            </div>
        </div>
    </div>


    <div class="site-footer">
        <div class="container">

           
                @Html.Partial("_SocialLikesPartial")
           

            <br />

            <div class="footer-links">
                <ul>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Advertising", "Advertising", "Home")</li>
                    <li>@Html.ActionLink("Add Agent", "Create", "Agents")</li>
                    
                </ul>
            </div>
            <div class="footer-cr">
                <p>
                    Copyright © 2005 - 2015 <a href="#">Rate-My-Agent.com</a> All Rights Reserved.
                </p>
                Rate and review agents in your local area. <a href="#">Sitemap</a>
            </div>
        </div>
    </div>

        


        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
</body>
</html>

RMA SITE CSHARP/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    @if (ViewBag.MetaDescription != "")
    {
        <meta name="description" content="@ViewBag.MetaDescription" />
    }

    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script type="text/javascript" src="~/Scripts/ckeditor/ckeditor.js"></script>

</head>
<body>



    <!--header-->
    <nav class="navbar navbar-default navbar-fixed-top site-nav">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#siteMenu" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index", "Home")">
                    <img src="@Url.Content("~/Resources/logo.png")" />
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="siteMenu">

                @Html.Partial("_LoginPartial")

                <ul class="nav navbar-nav navbar-right">
                    <li><a href="../Admin" class="nav-icon">ADMINISTRATION</a></li>
                    <li><a href="../AdminDataBank" class="nav-icon">DATA BANK</a></li>
                    <li><a href="../AdminTools" class="nav-icon">TOOLS</a></li>
                    <li><a href="../AdminSettings" class="nav-icon">SETTINGS</a></li>
                    <li><a href="#" class="nav-write"><i class="fa fa-edit"></i> &nbsp; </a></li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <!--end header-->
  


    <!--site main-->
    <div class="site-main">
        <div class="main-content">
            <div class="container">


                @RenderBody()

            </div>
        </div>
    </div>
    <!--end site main-->


    <div class="site-footer">
        <div class="container">
            <div class="footer-cr">
                <p>
                    Copyright © 2005 - 2015 <a href="#">Rate-My-Agent.com</a> All Rights Reserved.
                </p>
            
            </div>
        </div>
    </div>




    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

RMA SITE CSHARP/Views/Shared/_LayoutHome.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    @if (ViewBag.MetaDescription != "")
    {
        <meta name="description" content="@ViewBag.MetaDescription" />
    }

    @if (ViewBag.CanonicalUrl != "")
    {
        <link rel="canonical" href="@ViewBag.CanonicalUrl" />
    }

   

    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>





    @Html.Partial("_LayoutHeaderPartial")






    <div class="site-main">
        <div class="main-content">
          
                @RenderBody()



           
        </div>
    </div>


    <div class="site-footer">
        <div class="container">

           
                @Html.Partial("_SocialLikesPartial")
           

            <br />

            <div class="footer-links">
                <ul>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Advertising", "Advertising", "Home")</li>
                    <li>@Html.ActionLink("Add Agent", "Create", "Agents")</li>
                </ul>
            </div>
            <div class="footer-cr">
                <p>
                    Copyright © 2005 - 2015 <a href="#">Rate-My-Agent.com</a> All Rights Reserved.
                </p>
                Rate and review agents in your local area. <a href="#">Sitemap</a>
            </div>
        </div>
    </div>

        


        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
</body>
</html>

RMA SITE CSHARP/Views/Shared/_LayoutMembers.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    @if (ViewBag.MetaDescription != "")
    {
        <meta name="description" content="@ViewBag.MetaDescription" />
    }

    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Rate-My-Agent", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    @*<li>@Html.ActionLink("Reviews", "Index", "Reviews")</li>*@
                    <li style="margin-top:10px; margin-left:30px;">
                        @using (Html.BeginForm("Listings", "Search", FormMethod.Get))
                        {
                            @Html.TextBox("param")
                            @Html.Hidden("sortorder", "name_desc")
                            @Html.Hidden("v", "t")
                            <input type="submit" value="Search" />
                        }
                    </li>

                </ul>



                @Html.Partial("_LoginPartial")
                <ul class="nav navbar-nav" style="float:right">
                    <li>@Html.ActionLink("Write a Review", "Create", "Reviews")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">

        <div style="display:block;" align="left" valign="middle">
            <a href="~/real-estate">REAL ESTATE</a> --
            <a href="~/mortgage">MORTGAGE</a> --
            <a href="~/insurance">INSURANCE</a>
        </div>

        @RenderBody()
        <hr />

        <div style="text-align:left; float:right;">
            @Html.Partial("_SocialLikesPartial")
        </div>

        <footer>
            @Html.ActionLink("About", "About", "Home")
            &nbsp; || &nbsp;
            @Html.ActionLink("Contact", "Contact", "Home")
            &nbsp; || &nbsp;
            @Html.ActionLink("Advertising", "Advertising", "Home")
            <p>
                &copy;  2015 - Rate-My-Agent.com <br />
                <span style="font-size:9px"> Developed by thePhaze Project Systems </span>
            </p>
        </footer>
    </div>






    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

RMA SITE CSHARP/Views/Shared/_LayoutSingle.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    @if (ViewBag.MetaDescription != "")
    {
        <meta name="description" content="@ViewBag.MetaDescription" />
    }

    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    <link rel="stylesheet" href="~/Content/SingleReviewPrint.css" type="text/css" media="print" />
    @Scripts.Render("~/bundles/modernizr")

    <script type="text/javascript" src="~/Scripts/ckeditor/ckeditor.js"></script>

</head>
<body>

     


    <!--site main-->
    <div class="site-main">
        <div class="main-content">
            <div class="container">


                @RenderBody()

            </div>
        </div>
    </div>
    <!--end site main-->





    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

RMA SITE CSHARP/Views/Shared/_ListingsLayoutPartial.cshtml
@model PagedList.IPagedList<RMA_SITE.Models.Agent>
@using PagedList.Mvc;


<!--site main-->
<div class="site-main">
    <div class="page-content page-category">
        <div class="container">
            <div class="page-title-wrap">
                <h1 class="page-title">@ViewBag.Message</h1>

            </div>


            @if (Model.Count() > 0)
            {

                @Html.Partial("_AgentListingsPartial", Model)


            }
            else
            {
                <div><br />No Results.</div>
            }


            <hr />
            <p>
                @Html.Raw(ViewBag.CityPageContent)
            </p>

        </div>

      
    </div>
</div>
            
            
        

RMA SITE CSHARP/Views/Shared/_MembersArenaPartial.cshtml
<div style="width:100%; border:2px, solid, #808080; min-height: 200px;">

    hey

</div>

RMA SITE CSHARP/Views/Shared/_PartialAgentIndicator.cshtml
@model RMA_SITE.Models.Agent



@Model.first_name @Model.last_name

RMA SITE CSHARP/Views/Shared/_SearchBoxPartial.cshtml
<!--search-->
    <div class="page-search">
        <div class="container text-center">
            <form class="form-inline form-search" action="/Search/Listings" method="get">
                <div class="input-group">
                    <input type="text" class="form-control input-lg" placeholder="city, agent name or both..." size="40" id="param" name="param">
                    <input id="sortorder" name="sortorder" type="hidden" value="default" />
                    <input id="v" name="v" type="hidden" value="t" />
                    <span class="input-group-btn">
                        <button class="btn btn-default btn-lg btn-search"><span class="glyphicon glyphicon-search"></span> Search</button>
                    </span>
                </div>
            </form>
        </div>
    </div>
<!--end search-->


@*@using (Html.BeginForm("Listings", "Search", FormMethod.Get))
            {
    @Html.TextBox("param")
    @Html.Hidden("sortorder", "name_desc")
    @Html.Hidden("v", "t")
    <input type="submit" value="Search" />
}*@